# Generated by Django 5.0.7 on 2024-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_account_payment_card_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('checking', 'Checking'), ('investment', 'Investment'), ('credit', 'Credit')], max_length=50),
        ),
    ]
