# Generated by Django 5.0.7 on 2024-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='report_data',
            field=models.TextField(),
        ),
    ]
